modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="ChinaEX123, Fvue233"
description='''
Add VSS transactions for the villagers.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]] #optional
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ldlib2"
    type="required"
    versionRange="[2.2.41,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="viscript_shop"
    type="required"
    versionRange="[1.2.2.4,)"
    ordering="AFTER"
    side="BOTH"
